### PR TITLE
Remove `bitcoin_script_stack` dependency

### PR DESCRIPTION
**Pull request by Velnbur**
It uses `bitcoin@0.32.4` when we use only `bitcoin@0.31.0` from `bitvm` branch.

NOTE: `bitcoin_script_stack` has `bitvm` branch but conflicts with `lazy_static` versions from other crates.

### CODE REVIEW

**Comment by Velnbur** [comment]
Dependency tree from `use-one-bitcoin-version`:

image

**Comment by Velnbur** [comment]
After running `cargo update` in `main` we have:

image

**Comment by Velnbur** [comment]
Which is caused by multiple dependencies:

image

**Review by ZamDimon — APPROVED** [review]
LGTM

**Pull request merged**
